name: Release for PWA
on:
  push:
    tags:
      - "pwa@*"
jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    permissions:
      contents: read
      actions: read
      security-events: write
  release:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Push to branch `release`
        run: |
          git branch release -f
          git push origin release -f

      - name: Generate changelog
        id: changelog
        uses: manga-raiku/changelog-generator@v4.0.1-patch2
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          match-tag: pwa@*

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

